NON_WORDS  = set((
    'a', 'a-si', 'acela', 'acesta', 'acolo',
    'ai', 'aiurea', 'ajunge', 'al', 'ala', 'alaturi',
    'ale', 'alo', 'altceva', 'altcineva', 'amandoi', 'ani', 'aproape',
    'asa', 'asta', 'asupra', 'b', 'bre', 'buna', 'c', 'ca', 'cand',
    'care', 'cat', 'catre', 'ce', 'cea', 'cel', 'celalalt', 'cei',
    'ceva', 'cine', 'cineva', 'conform', 'cu', 'cui', 'd', 'da',
    'daca', 'dar', 'datorita', 'de', 'dealungul', 'deci', 'departe',
    'despre', 'din', 'dinainte', 'dintr-o', 'dintr-un', 'dintre',
    'du-te', 'dupa', 'e', 'f', 'fara', 'fiecare', 'fiindca', 'g',
    'h', 'hai', 'ham', 'hau', 'i', 'i-a', 'i-ai',
    'i-am', 'i-ati', 'i-au', 'iar', 'imbi', 'imi', 'in', 'inainte',
    'insa', 'intr-o', 'intr-un', 'intre', 'intru', 'j', 'k', 'l',
    'l-a', 'l-ai', 'l-am', 'l-ati', 'la', 'langa', 'li-l', 'lungul',
    'm', 'm-ai', 'm-am', 'ma', 'mata', 'mea', 'mersi', 'mi-am',
    'miau', 'mine', 'multi', 'multumesc', 'n', 'ni-l', 'nimeni',
    'nimic', 'niste', 'no', 'noroc', 'nu-i', 'nu-s', 'o',
    'oare', 'ori', 'oricare', 'orice', 'oricine', 'p', 'pa',
    'pana', 'pare', 'pe', 'pentru', 'peste', 'precum', 'prin',
    'printr-o', 'printr-un', 'pt', 'q', 'r', 'rau',
    'revedere', 'rog', 's', 's-a', 's-au', 'sa', 'sal', 'salut',
    'salve', 'sau', 'se', 'seara', 'servus', 'si', 'sictir',
    'spre', 'sub', 't', 'te', 'totusi', 'u', 'un',
    'unei', 'unor', 'unui', 'unul', 'v', 'va', 'vai', 'vi-l',
    'via', 'vezi', 'w', 'x', 'y', 'z', 'zau'
))
